server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/xx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: xx
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimumIdle: 1
      idle-timeout: 600000
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 300000
    password: xx
  jpa:
    hibernate:
      ddl-auto: none # 此处必须设置为none，需要覆盖的自行前往应用yml配置
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  freemarker:
    content-type: text/html
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    parser: {"ALLOW_COMMENTS": true}
  task:
    execution:
      thread-name-prefix: jcloud-thread-pool-
      pool:
        core-size: 5 # 核心线程数 cpu core + 1
        max-size: 10 # 最大线程数
        queue-capacity: 100 # 队列容量，实际容纳的线程数 = 队列容量 + 最大线程数，优先使用队列
        keep-alive: 60s # 线程等待时间,如果60s没收到任务，则销毁线程
      shutdown:
        await-termination: true # 应用关闭时，是否等待所有线程执行完毕后关闭
        await-termination-period: 60s # 关闭时最大等待时长

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true # 对map解析时，当数据为空时，不忽略该Key
    cache-enabled: true         # 使用二级缓存
  global-config:
    db-config:
      select-strategy: IGNORED
      insert-strategy: IGNORED
      update-strategy: IGNORED
      id-type: auto
springfox:
  documentation:
    enabled: true #开启swagger
    swagger-ui:
      base-url: /dpath
    swagger:
      v2:
        path: /document/api

swagger: # swagger 配置
  basePackage: com.jcloud
  description: api文档
system:
  extPath: D:/upload # 外部地址，用于存放一些静态文件，可以通过/ext 获取
  domain: www.pinzhi365.com # host
  superPassword: xxxxd # 超级密码
  default-password: 123456 # 用户默认密码
  openLoginCode: false # 是否开启登录验证码
  notAuthUrls:
    - /auth/**
    - /*.* # 匹配所有静态文件
    - /index # 首页
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: jtoken
  # token有效期，单位s 默认1天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  #activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
